version: "3.9"

services:
  db:
    image: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=Support
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
  web:
    build:
      context: ""

    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: redis
    restart: always
    command: redis-server
    ports:
      - '6379:6379'
  celery:
    build: .
    command: celery -A support worker -B
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - web
      - redis
volumes:
  postgres_data: