version: "3.9"

services:
  db:
    image: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${NAME}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
  web:
    build:
      context: ""
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: redis
    restart: always
    command: redis-server
    ports:
      - '6379:6379'
  celery:
    build:
      context: .
      dockerfile: celery/Dockerfile
    command: celery -A support worker -B
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - db
      - redis
volumes:
  postgres_data:
